public class CodeGenerator {

    private final SymbolTable symbolTable;
    private final StringBuilder output = new StringBuilder();
    private int indentLevel = 2;

    public CodeGenerator(SymbolTable symbolTable) {
        this.symbolTable = symbolTable;
    }

    public String generate(ASTNode program) {
        output.setLength(0);

        emit(0, "// Generated by Bhasha Compiler");
        emit(0, "public class ShobujOutput {");
        emit(1, "public static void main(String[] args) {");

        for (ASTNode statement : program.statements) {
            generateStatement(statement);
        }

        emit(1, "}");
        emit(0, "}");

        return output.toString();
    }

    private void generateStatement(ASTNode node) {
        if (node == null) return;

        switch (node.nodeType) {
            case DECL -> {
                String javaType = node.dataType.equals("সংখ্যা") ? "int" : "String";
                String javaName = symbolTable.javaName(node.value);
                emit(indentLevel, javaType + " " + javaName + " = " + generateExpression(node.right) + ";");
            }

            case ASSIGN -> {
                String javaName = symbolTable.javaName(node.value);
                emit(indentLevel, javaName + " = " + generateExpression(node.right) + ";");
            }

            case PRINT -> {
                emit(indentLevel, "System.out.println(" + generateExpression(node.right) + ");");
            }

            case IF -> {
                emit(indentLevel, "if (" + generateExpression(node.condition) + ") {");
                indentLevel++;

                for (ASTNode statement : node.thenBody) {
                    generateStatement(statement);
                }

                indentLevel--;

                if (!node.elseBody.isEmpty()) {
                    emit(indentLevel, "} else {");
                    indentLevel++;

                    for (ASTNode statement : node.elseBody) {
                        generateStatement(statement);
                    }

                    indentLevel--;
                }

                emit(indentLevel, "}");
            }

            case WHILE -> {
                emit(indentLevel, "while (" + generateExpression(node.condition) + ") {");
                indentLevel++;

                for (ASTNode statement : node.loopBody) {
                    generateStatement(statement);
                }

                indentLevel--;

                emit(indentLevel, "}");
            }

            default -> {
            }
        }
    }

    private String generateExpression(ASTNode node) {
        if (node == null) return "0";

        return switch (node.nodeType) {
            case NUMBER -> node.value;
            case STRING -> "\"" + escapeString(node.value) + "\"";
            case IDENTIFIER -> symbolTable.javaName(node.value);
            case BINOP -> "(" + generateExpression(node.left) + " " + node.value + " " + generateExpression(node.right) + ")";
            default -> "0";
        };
    }

    private String escapeString(String text) {
        return text.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
    }

    private void emit(int indent, String line) {
        output.append("    ".repeat(indent)).append(line).append("\n");
    }
}