public class CodeGenerator {

    private final SymbolTable symbolTable;
    private final StringBuilder sb = new StringBuilder();
    private int indentLevel = 2;

    public CodeGenerator(SymbolTable symbolTable) {
        this.symbolTable = symbolTable;
    }

    public String generate(ASTNode program) {
        sb.setLength(0);

        emit(0, "// Generated by Bhasha Compiler");
        emit(0, "// Bangla source code converted into Java");
        emit(0, "public class ShobujOutput {");
        emit(1, "public static void main(String[] args) {");

        for (ASTNode statement : program.statements) {
            genStmt(statement);
        }

        emit(1, "}");
        emit(0, "}");

        return sb.toString();
    }

    private void genStmt(ASTNode node) {
        if (node == null) {
            return;
        }

        switch (node.nodeType) {
            case DECL -> {
                String javaType = node.dataType.equals("সংখ্যা") ? "int" : "String";
                String javaName = symbolTable.javaName(node.value);
                emit(indentLevel, javaType + " " + javaName + " = " + genExpr(node.right) + ";");
            }

            case ASSIGN -> {
                String javaName = symbolTable.javaName(node.value);
                emit(indentLevel, javaName + " = " + genExpr(node.right) + ";");
            }

            case PRINT -> emit(indentLevel, "System.out.println(" + genExpr(node.right) + ");");

            case IF -> {
                emit(indentLevel, "if (" + genExpr(node.condition) + ") {");
                indentLevel++;

                for (ASTNode statement : node.thenBody) {
                    genStmt(statement);
                }

                indentLevel--;

                if (!node.elseBody.isEmpty()) {
                    emit(indentLevel, "} else {");
                    indentLevel++;

                    for (ASTNode statement : node.elseBody) {
                        genStmt(statement);
                    }

                    indentLevel--;
                }

                emit(indentLevel, "}");
            }

            case WHILE -> {
                emit(indentLevel, "while (" + genExpr(node.condition) + ") {");
                indentLevel++;

                for (ASTNode statement : node.loopBody) {
                    genStmt(statement);
                }

                indentLevel--;
                emit(indentLevel, "}");
            }

            default -> {
            }
        }
    }

    private String genExpr(ASTNode node) {
        if (node == null) {
            return "null";
        }

        return switch (node.nodeType) {
            case NUMBER -> node.value;
            case STRING -> "\"" + escapeString(node.value) + "\"";
            case IDENTIFIER -> symbolTable.javaName(node.value);
            case BINOP -> "(" + genExpr(node.left) + " " + node.value + " " + genExpr(node.right) + ")";
            default -> "0";
        };
    }

    private String escapeString(String s) {
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
    }

    private void emit(int indent, String line) {
        sb.append("    ".repeat(indent)).append(line).append("\n");
    }
}