// Generated by Bhasha Compiler
// Bangla source code converted into Java
public class ShobujOutput {
    public static void main(String[] args) {
        int v0 = 10;
        int v1 = 5;
        int v2 = (v0 + v1);
        int v3 = (v0 * v1);
        String v4 = "হিসাব সম্পন্ন";
        System.out.println("যোগফল:");
        System.out.println(v2);
        System.out.println("গুণফল:");
        System.out.println(v3);
        System.out.println(v4);
    }
}
